apiVersion: v2
name: safe-transaction-service
version: 0.1.0
appVersion: "v5.5.0"
description: A Helm chart to deploy safe-transaction-service
keywords:
  - safe
  - stack
  - web3
  - wallet
  - smart-account
home: https://safe.global
icon: https://safe-global.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F640c7ac9-75c9-4d75-875d-56057030fb71%2FSAFE_token_logo.png?table=block&id=7d9ad728-dd7e-4623-9149-d2afc766b4f0&spaceId=5010e4ee-a4be-4f75-a21f-79bde3054f7f&width=260&userId=&cache=v2
sources:
  - https://github.com/5afe/safe-helm-charts/tree/main/charts/safe-transaction-service
  - https://github.com/safe-global/safe-transaction-service
maintainers:
  - name: gjeanmart
    email: greg@safe.global
dependencies:
  - name: postgresql
    version: 14.3.3
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: safe-transaction-service-postgresql.enabled
    alias: safe-transaction-service-postgresql
  - name: redis
    version: 19.6.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: safe-transaction-service-redis.enabled
    alias: safe-transaction-service-redis
  - name: rabbitmq
    version: 14.6.5
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: safe-transaction-service-rabbitmq.enabled
    alias: safe-transaction-service-rabbitmq