# Default values for safe-transaction-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Provide a name in place of safe-transaction-service for `app:` labels
##
nameOverride: ""
## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""
## Reference to one or more secrets to be used when pulling images
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
##
imagePullSecrets: []

replicaCount: 1

image:
  repository: safeglobal/safe-transaction-service
  tag: latest
  pullPolicy: Always

extraEnv: []

config:
  debug: true
  queues: default,indexing,contracts,tokens,notifications,webhooks
  secretKey: "Very-secure-secret-string" # change me
  csrf:
    trustedOrigins: "https://safe-wallet.minikube.net"
  node:
    url: # leave empty if you use ganache
    useGanacheNode: true
  database:
    url: # leave empty if postgresql.enabled=true (e.g plsql://user:pw@host:port/db)
    runMigration: true
  redis: 
    url: # leave empty if redis.enabled=true e.g redis://
  rabbitmq: 
    url: # leave empty if rabbitmq.enabled=true e.g amqp://
  admin:
    auth:
      enabled: true
      username: root  # change me
      password: root123  # change me
      email: root@example.com

scheduler:
  nodeSelector: {}
  affinity: {}
  tolerations: {}
  securityContext: {}
  podSecurityContext: {}
  resources:
    requests:
      memory: "100Mi"
      cpu: "50m"
    limits:
      memory: "200Mi"
      cpu: "100m"

indexer:
  nodeSelector: {}
  affinity: {}
  tolerations: {}
  securityContext: {}
  podSecurityContext: {}
  resources: 
    requests:
      memory: "300Mi"
      cpu: "50m"
    limits:
      memory: "600Mi"
      cpu: "100m"
      
web:
  nodeSelector: {}
  affinity: {}
  tolerations: {}
  securityContext: {}
  podSecurityContext: {}
  resources:
    requests:
      memory: "1000Mi"
      cpu: "500m"
    limits:
      memory: "2000Mi"
      cpu: "1000m"

ingress:
  enabled: true
  ingressClassName: nginx
  host: txs-service.minikube.net
  annotations: 
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "false"

##
## Ganache (test) node configuration
##
ganacheNode:
  enabled: true
  config:
    mnemonic: "test test test test test test test test test test test junk"
    chainId: 1337
    persistence:
      storageClass: standard
      size: 100Mi
  ingress:
    enabled: true
    ingressClassName: nginx
    host: node.minikube.net
    annotations: {}

safe-transaction-service-postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: safe
        password: changeme
        database: txs
  primary:
    persistence:
      enabled: true
      storageClass: "standard"
      size: 100Mi

safe-transaction-service-redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      storageClass: "standard"
      size: 100Mi
  replica:
    replicaCount: 0

safe-transaction-service-rabbitmq:
  enabled: true
  auth:
    username: guest
    password: guest
  persistence:
    enabled: true
    storageClass: "standard"
    size: 100Mi