{{- if not .Values.config.redis.useExisting }}
---
apiVersion: v1
kind: Service

metadata:
  name: {{ include "safe-transaction-service.fullname" . }}-redis

spec:
  selector:
    app: {{ include "safe-transaction-service.fullname" . }}-redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
---
{{- end }}