{{- if and (.Values.cgwService.enabled) (not .Values.cgwService.config.redis.useExisting) }}
---
apiVersion: v1
kind: Service

metadata:
  name: {{ include "safe-client-gateway.fullname" . }}-redis

spec:
  selector:
    app: {{ include "safe-client-gateway.fullname" . }}-redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
---
{{- end }}