apiVersion: v1
entries:
  safe-client-gateway:
  - apiVersion: v2
    appVersion: v1.51.0
    created: "2024-07-25T16:12:23.592306+02:00"
    description: A Helm chart to deploy safe-client-gateway
    digest: a6fbd3fb8712b2ba5ff3cf54cdf8b5057da0f3a40bb34e2dd8c5b02991e355d3
    home: https://safe.global
    icon: https://file.notion.so/f/f/5010e4ee-a4be-4f75-a21f-79bde3054f7f/9ad9e60c-dd0d-4783-9a32-100d888a075f/Safe_Logos_Symbol_Black.png?id=c59948aa-158b-4f54-8ab7-9c30cae68fee&table=block&spaceId=5010e4ee-a4be-4f75-a21f-79bde3054f7f&expirationTimestamp=1721916000000&signature=8RXoougMiHsHbAe6mc4ieAG-MGK-W8IEoMvknbUJp0c&downloadName=Safe_Logos_Symbol_Black.png
    keywords:
    - safe
    - stack
    - web3
    - wallet
    - smart-account
    maintainers:
    - email: greg@safe.global
      name: gjeanmart
    name: safe-client-gateway
    sources:
    - https://github.com/5afe/safe-helm-charts/tree/main/charts/safe-client-gateway
    - https://github.com/safe-global/safe-client-gateway/
    urls:
    - https://5afe.github.io/safe-helm-charts/charts/packages/safe-client-gateway-0.1.0.tgz
    version: 0.1.0
  safe-config-service:
  - apiVersion: v2
    appVersion: v2.83.0
    created: "2024-07-25T16:12:23.592684+02:00"
    description: A Helm chart to deploy safe-config-service
    digest: b379c7874bd028da2ca910ea1d1156feee82975e20380abaa1d9f22eb089e741
    home: https://safe.global
    icon: https://file.notion.so/f/f/5010e4ee-a4be-4f75-a21f-79bde3054f7f/9ad9e60c-dd0d-4783-9a32-100d888a075f/Safe_Logos_Symbol_Black.png?id=c59948aa-158b-4f54-8ab7-9c30cae68fee&table=block&spaceId=5010e4ee-a4be-4f75-a21f-79bde3054f7f&expirationTimestamp=1721916000000&signature=8RXoougMiHsHbAe6mc4ieAG-MGK-W8IEoMvknbUJp0c&downloadName=Safe_Logos_Symbol_Black.png
    keywords:
    - safe
    - stack
    - web3
    - wallet
    - smart-account
    maintainers:
    - email: greg@safe.global
      name: gjeanmart
    name: safe-config-service
    sources:
    - https://github.com/5afe/safe-helm-charts/tree/main/charts/safe-config-service
    - https://github.com/safe-global/safe-config-service
    urls:
    - https://5afe.github.io/safe-helm-charts/charts/packages/safe-config-service-0.1.0.tgz
    version: 0.1.0
  safe-stack:
  - apiVersion: v2
    appVersion: 2024-07-24_001
    created: "2024-07-25T16:12:23.594476+02:00"
    dependencies:
    - condition: safe-transaction-service.enabled
      name: safe-transaction-service
      repository: file://../safe-transaction-service
      version: 0.1.0
    - condition: safe-config-service.enabled
      name: safe-config-service
      repository: file://../safe-config-service
      version: 0.1.0
    - condition: safe-client-gateway.enabled
      name: safe-client-gateway
      repository: file://../safe-client-gateway
      version: 0.1.0
    - condition: safe-wallet-web.enabled
      name: safe-wallet-web
      repository: file://../safe-wallet-web
      version: 0.1.0
    description: A Helm chart to deploy the full Safe{Stack} inclusing txs-service,
      cfg-service, cgw-service and wallet-web
    digest: 7829086410cad2fa211a6c9eb78ed608ce3e06dc7217edd99f8002350833126a
    home: https://safe.global
    icon: https://file.notion.so/f/f/5010e4ee-a4be-4f75-a21f-79bde3054f7f/9ad9e60c-dd0d-4783-9a32-100d888a075f/Safe_Logos_Symbol_Black.png?id=c59948aa-158b-4f54-8ab7-9c30cae68fee&table=block&spaceId=5010e4ee-a4be-4f75-a21f-79bde3054f7f&expirationTimestamp=1721916000000&signature=8RXoougMiHsHbAe6mc4ieAG-MGK-W8IEoMvknbUJp0c&downloadName=Safe_Logos_Symbol_Black.png
    keywords:
    - safe
    - stack
    - web3
    - wallet
    - smart-account
    maintainers:
    - email: greg@safe.global
      name: gjeanmart
    name: safe-stack
    sources:
    - https://github.com/5afe/safe-helm-charts/tree/main/charts/safe-stack
    - https://github.com/safe-global/safe-infrastructure
    urls:
    - https://5afe.github.io/safe-helm-charts/charts/packages/safe-stack-0.1.0.tgz
    version: 0.1.0
  safe-transaction-service:
  - apiVersion: v2
    appVersion: v5.5.0
    created: "2024-07-25T16:12:23.594944+02:00"
    description: A Helm chart to deploy safe-transaction-service
    digest: fb2388e168b09db259a07ec0d1e4649b6f3ac0785321fce1a71d52e363e5f5b1
    home: https://safe.global
    icon: https://file.notion.so/f/f/5010e4ee-a4be-4f75-a21f-79bde3054f7f/9ad9e60c-dd0d-4783-9a32-100d888a075f/Safe_Logos_Symbol_Black.png?id=c59948aa-158b-4f54-8ab7-9c30cae68fee&table=block&spaceId=5010e4ee-a4be-4f75-a21f-79bde3054f7f&expirationTimestamp=1721916000000&signature=8RXoougMiHsHbAe6mc4ieAG-MGK-W8IEoMvknbUJp0c&downloadName=Safe_Logos_Symbol_Black.png
    keywords:
    - safe
    - stack
    - web3
    - wallet
    - smart-account
    maintainers:
    - email: greg@safe.global
      name: gjeanmart
    name: safe-transaction-service
    sources:
    - https://github.com/5afe/safe-helm-charts/tree/main/charts/safe-transaction-service
    - https://github.com/safe-global/safe-transaction-service
    urls:
    - https://5afe.github.io/safe-helm-charts/charts/packages/safe-transaction-service-0.1.0.tgz
    version: 0.1.0
  safe-wallet-web:
  - apiVersion: v2
    appVersion: v1.39.2
    created: "2024-07-25T16:12:23.595193+02:00"
    description: A Helm chart to deploy safe-wallet-web
    digest: 7036987b648350b4d498a09d707dc13257876de2156e9e1286691de47b22d0d2
    home: https://safe.global
    icon: https://file.notion.so/f/f/5010e4ee-a4be-4f75-a21f-79bde3054f7f/9ad9e60c-dd0d-4783-9a32-100d888a075f/Safe_Logos_Symbol_Black.png?id=c59948aa-158b-4f54-8ab7-9c30cae68fee&table=block&spaceId=5010e4ee-a4be-4f75-a21f-79bde3054f7f&expirationTimestamp=1721916000000&signature=8RXoougMiHsHbAe6mc4ieAG-MGK-W8IEoMvknbUJp0c&downloadName=Safe_Logos_Symbol_Black.png
    keywords:
    - safe
    - stack
    - web3
    - wallet
    - smart-account
    maintainers:
    - email: greg@safe.global
      name: gjeanmart
    name: safe-wallet-web
    sources:
    - https://github.com/5afe/safe-helm-charts/tree/main/charts/safe-wallet-web
    - https://github.com/safe-global/safe-wallet-web
    urls:
    - https://5afe.github.io/safe-helm-charts/charts/packages/safe-wallet-web-0.1.0.tgz
    version: 0.1.0
generated: "2024-07-25T16:12:23.591864+02:00"
