apiVersion: v1
entries:
  safe-stack:
  - apiVersion: v2
    appVersion: 2024-07-24_001
    created: "2024-07-24T15:14:44.112974+02:00"
    description: A Helm chart to deploy Safe stack
    digest: 6d6d3c8f35cc454fca86f3621504a67d87536d4a6dcef439b16c241c4e0ffb83
    home: https://safe.global
    icon: https://file.notion.so/f/f/5010e4ee-a4be-4f75-a21f-79bde3054f7f/9ad9e60c-dd0d-4783-9a32-100d888a075f/Safe_Logos_Symbol_Black.png?id=c59948aa-158b-4f54-8ab7-9c30cae68fee&table=block&spaceId=5010e4ee-a4be-4f75-a21f-79bde3054f7f&expirationTimestamp=1721916000000&signature=8RXoougMiHsHbAe6mc4ieAG-MGK-W8IEoMvknbUJp0c&downloadName=Safe_Logos_Symbol_Black.png
    keywords:
    - safe
    - stack
    - web3
    - aa
    maintainers:
    - email: greg@safe.global
      name: gjeanmart
    name: safe-stack
    sources:
    - https://github.com/5afe/safe-helm-charts/tree/main/charts/safe-stack
    urls:
    - safe-stack-0.1.0.tgz
    version: 0.1.0
generated: "2024-07-24T15:14:44.112018+02:00"
