{{- if .Values.ganacheNode.enabled }}
---
apiVersion: v1
kind: Service

metadata:
  name: {{ include "safe-stack.fullname" . }}-ganache-node

spec:
  selector:
    app: {{ include "safe-stack.fullname" . }}-ganache-node
  ports:
    - name: node-rpc
      protocol: TCP
      port: 8545
      targetPort: 8545
---
{{- end }}