{{- if not .Values.config.database.useExisting }}
---
apiVersion: v1

kind: Service

metadata:
  name: {{ include "safe-config-service.fullname" . }}-postgresql

spec:
  selector:
    app: {{ include "safe-config-service.fullname" . }}-postgresql
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
---
{{- end }}