{{- if .Values.cfgService.enabled }}
---
apiVersion: v1

kind: Service

metadata:
  name: {{ include "safe-stack.fullname" . }}-cfg-web

spec:
  selector:
    app: {{ include "safe-stack.fullname" . }}-cfg-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
---
{{- end }}