{{- if and (.Values.txsService.enabled) (not .Values.txsService.config.database.useExisting) }}
---
apiVersion: v1

kind: Service

metadata:
  name: {{ include "safe-stack.fullname" . }}-txs-db

spec:
  selector:
    app: {{ include "safe-stack.fullname" . }}-txs-db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
---
{{- end }}