{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: {{ include "safe-config-service.fullname" . }}-web

  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{ end }}

spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - "{{ .Values.ingress.tls.host }}"
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
        - path: /
          pathType: 'Exact'
          backend:
            service:
              name: {{ include "safe-config-service.fullname" . }}-web
              port:
                number: 80
        - path: /api
          pathType: 'Prefix'
          backend:
            service:
              name: {{ include "safe-config-service.fullname" . }}-web
              port:
                number: 80
        - path: /static
          pathType: 'Prefix'
          backend:
            service:
              name: {{ include "safe-config-service.fullname" . }}-web
              port:
                number: 80
        - path: /media
          pathType: 'Prefix'
          backend:
            service:
              name: {{ include "safe-config-service.fullname" . }}-web
              port:
                number: 80
        - path: /check
          pathType: 'Prefix'
          backend:
            service:
              name: {{ include "safe-config-service.fullname" . }}-web
              port:
                number: 80
        - path: /admin
          pathType: 'Prefix'
          backend:
            service:
              name: {{ include "safe-config-service.fullname" . }}-web
              port:
                number: 80
---
{{- end }}