{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: {{ include "safe-client-gateway.fullname" . }}-web

  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{ end }}

spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: /
          pathType: 'Prefix'
          backend:
            service:
              name: {{ include "safe-client-gateway.fullname" . }}-web
              port:
                number: 80

---
{{- end }}