{{- if .Values.cgwService.enabled }}
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "safe-client-gateway.fullname" . }}-web

spec:
  replicas: {{ .Values.cgwService.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "safe-client-gateway.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "safe-client-gateway.fullname" . }}-web
    spec:
      containers:
        - name: web
          image: "{{ .Values.cgwService.image.repository }}:{{ .Values.cgwService.image.tag }}"
          imagePullPolicy: {{ .Values.cgwService.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "safe-client-gateway.fullname" . }}-env
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
            timeoutSeconds: 10
            periodSeconds: 30
          {{- with .Values.cgwService.web.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cgwService.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with .Values.cgwService.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cgwService.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cgwService.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cgwService.web.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
{{- end }}