{{- if and .Values.txsService.enabled (not .Values.txsService.config.redis.useExisting)}}
---
apiVersion: v1
kind: Service

metadata:
  name: {{ include "safe-stack.fullname" . }}-txs-redis

spec:
  selector:
    app: {{ include "safe-stack.fullname" . }}-txs-redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
---
{{- end }}