{{- if .Values.txsService.enabled }}
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "safe-transaction-service.fullname" . }}-scheduler

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "safe-transaction-service.fullname" . }}-scheduler
  template:
    metadata:
      labels:
        app: {{ include "safe-transaction-service.fullname" . }}-scheduler
    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.txsService.image.repository }}:{{ .Values.txsService.image.tag }}"
          imagePullPolicy: {{ .Values.txsService.image.pullPolicy }}
          command: ["docker/web/celery/scheduler/run.sh"]
          env:
            - name: ETHEREUM_NODE_URL
              {{- if .Values.txsService.config.node.useGanacheNode }}
              value: "http://{{ include "safe-transaction-service.fullname" . }}-ganache-node:8545"
              {{- else }}
              value: {{ .Values.txsService.config.node.url }}
              {{- end }}
            - name: WORKER_QUEUES
              value: {{ .Values.txsService.config.queues }}
          envFrom:
            - configMapRef:
                name: {{ include "safe-transaction-service.fullname" . }}-env
  
          {{- with .Values.txsService.scheduler.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.txsService.scheduler.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.txsService.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.txsService.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.txsService.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.txsService.scheduler.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}