{{- if .Values.txsService.enabled }}
---
apiVersion: v1
kind: Service

metadata:
  name: {{ include "safe-transaction-service.fullname" . }}-web

spec:
  selector:
    app: {{ include "safe-transaction-service.fullname" . }}-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
---
{{- end }}