{{- if .Values.ganacheNode.enabled }}
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "safe-transaction-service.fullname" . }}-ganache-node

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "safe-transaction-service.fullname" . }}-ganache-node
  template:
    metadata:
      labels:
        app: {{ include "safe-transaction-service.fullname" . }}-ganache-node
    spec:
      containers:
        - name: ganache-node
          image: "{{ .Values.ganacheNode.image.repository }}:{{ .Values.ganacheNode.image.tag }}"
          imagePullPolicy: {{ .Values.ganacheNode.image.pullPolicy }}
          ports:
            - name: node-rpc
              containerPort: 8545
          env:
            - name: MNEMONIC
              value: "{{ .Values.ganacheNode.config.mnemonic }}"
            - name: CHAIN_ID
              value: "{{ .Values.ganacheNode.config.chainId }}"
            - name: DETERMINISTIC_DEPLOYMENT
              value: "{{ .Values.ganacheNode.config.deterministicDeployment }}"
          volumeMounts:
            - name: ganache-node-claim
              mountPath: /db
      volumes:
        - name: ganache-node-claim
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-ganache-node-claim0
---
{{- end }}