{{- if and .Values.ganacheNode.enabled .Values.ganacheNode.ingress.enabled}}
apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: {{ include "safe-transaction-service.fullname" . }}-ganache-node

  annotations: 
    {{- range $k, $v := .Values.ganacheNode.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{ end }}

spec:
  # notice: ref: https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/
  ingressClassName: {{ .Values.ganacheNode.ingress.ingressClassName }}
  {{- if .Values.ganacheNode.ingress.tls.enabled }}
  tls:
    - hosts:
        - "{{ .Values.ganacheNode.ingress.host }}"
      secretName: {{ .Values.ganacheNode.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: "{{ .Values.ganacheNode.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "safe-transaction-service.fullname" . }}-ganache-node
                port:
                  number: 8545
---
{{- end }}