{{- if .Values.ganacheNode.enabled }}
---
apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: {{ .Release.Name }}-ganache-node-claim0

spec:
  storageClassName: {{ .Values.ganacheNode.config.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ganacheNode.config.persistence.size }}
---
{{- end }}