{{- if .Values.walletWeb.enabled }}
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "safe-stack.fullname" . }}-wallet

spec:
  replicas:  {{ .Values.walletWeb.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "safe-stack.fullname" . }}-wallet
  template:
    metadata:
      labels:
        app: {{ include "safe-stack.fullname" . }}-wallet
    spec:
      containers:
        - name: wallet
          image: "{{ .Values.walletWeb.image.repository }}:{{ .Values.walletWeb.image.tag }}"
          imagePullPolicy: {{ .Values.walletWeb.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ include "safe-stack.fullname" . }}-wallet-env
#          livenessProbe:
#            exec:
#              command:
#                - ----something here----
#            failureThreshold: 3
#            initialDelaySeconds: 420 # 7 minutes, yeah the UI takes it's time to start ...
#            periodSeconds: 60
#            timeoutSeconds: 30
---
{{- end }}