{{- if .Values.txsService.enabled }}
---
apiVersion: v1
kind: Service

metadata:
  name: {{ include "safe-stack.fullname" . }}-txs-web

spec:
  selector:
    app: {{ include "safe-stack.fullname" . }}-txs-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
---
{{- end }}