{{- if .Values.walletWeb.enabled }}
---
apiVersion: v1

kind: Service

metadata:
  name: {{ include "safe-wallet-web.fullname" . }}

spec:
  selector:
    app: {{ include "safe-wallet-web.fullname" . }}
  ports:
    - name: https
      protocol: TCP
      port: 443 
      targetPort: 3000 
---
{{- end }}