{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: {{ include "safe-wallet-web.fullname" . }}

  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{ end }}

spec:
  # notice: ref: https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/
  ingressClassName: {{ .Values.ingress.ingressClassName }}

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "safe-wallet-web.fullname" . }}
                port:
                  number: 443
---
{{- end }}